### ISSUE TITLE
What version of Django is required?

### ISSUE THREAD

**Issue by markkennedy** [moorinl/wagtail-themes#12]
I'm running Django 1.8.18. When trying to run `wagtail-themes` I get an error from `wagtailthemes.middleware` because it imports `django.utils.deprecation.MiddlewareMixin`, which wasn't introduced until Django 1.10.

The `setup.py` file for this project only requires Django 1.8. Should it be updated to require 1.10, or can the middleware be changed to not inherit from `django.utils.deprecation.MiddlewareMixin`?

**Comment by robmoorman** [comment]
Thanks for the nice, I added a tiny note https://github.com/moorinteractive/wagtail-themes#compatibility
