### ISSUE TITLE
ThemeLoader in  app directories

### ISSUE THREAD

**Issue by TonisPiip** [moorinl/wagtail-themes#24]
I remember testing this and found that there's no way to have the theme'd templates in APP folders. But I might be mistaken.

Wouldn't it also make sense to be able to put theme templates there?
Or have an option to have them there? 

It's unclear to me which template would be found first in this case:
```
project/myapp/templates/themes/foo_theme/template.html
project/templates/themes/foo_theme/template.html
```
However if the loader is a separate loader, that can be determined by how the order in `loaders`

**Comment by robmoorman** [comment]
He @TonisPiip this is default django ordering, the app which is found first will be picked. By default all templates are found per app, so each app could have `themes/foo_theme` in this case.

Notice the docs that the `wagtailthemes.loaders.ThemeLoader` is put first (it get its dirs from the default file loader, just an extend of it)
