### ISSUE TITLE
ThemeMiddleware throws error when no default site is set

### ISSUE THREAD

**Issue by robmoorman** [moorinl/wagtail-themes#9]

**Comment by marquicus** [comment]
It throws the error even in the configuration ThemeMiddleware is after SiteMiddleware, all sites and admin stop working:

Request Method: | GET
-- | --
http://localhost:8000/cms/sites/
2.0.13
ImproperlyConfigured
ThemeMiddleware must be added after SiteMiddleware
/home/marp/.virtualenvs/wagtail/lib/python3.6/site-packages/wagtailthemes/middleware.py in process_request, line 17
/home/marp/.virtualenvs/wagtail/bin/python
3.6.6
